version: "3.4"

services:

  db:
    image: postgres:10.2
    environment:
      POSTGRES_DB: "webdb"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "fH98GvSx6vaLGttRTbnLdGhe"

  web:
    image: jdavid5815/django-demo:1.0
    working_dir: /app/mysite
    volumes:
      - /Users/jdavid/IntroDocker/django/app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
